# Generated by Django 4.2.1 on 2023-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='x',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
