# Generated by Django 4.2.1 on 2023-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_skill_profile_x1_profile_x2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description2',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description3',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
