# Generated by Django 4.2.1 on 2023-06-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_description_post_description2_post_description3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
