# Generated by Django 4.2.1 on 2023-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description4',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
